# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)
opt_out_usage

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Deploy a new version to the Google Play Beta lane"
  lane :beta do
    setup_ci
    gradle(
      task: "clean bundleRelease assembleRelease"
    )
    upload_to_play_store(
      track: 'closed-beta', 
      aab: '../build/app/outputs/bundle/release/app-release.aab',
      skip_upload_apk: true, 
      skip_upload_metadata: true, 
      skip_upload_changelogs: true, 
      skip_upload_images: true, 
      skip_upload_screenshots: true
    )
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    setup_ci
    gradle(task: "clean bundleRelease assembleRelease")
    upload_to_play_store( 
      aab: '../build/app/outputs/bundle/release/app-release.aab',
      skip_upload_apk: true, 
      skip_upload_metadata: true, 
      skip_upload_changelogs: true, 
      skip_upload_images: true, 
      skip_upload_screenshots: true
    )
  end
end
